spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/walletdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
